run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: true
  max-issues-per-linter: 0
  max-same-issues: 0
  skip-files:
    - ".*\\_test\\.go$"
linters:
  enable-all: true
  disable:
    - scopelint
    - deadcode
    - interfacer
    - exhaustivestruct
    - maligned
    - nosnakecase
    - varcheck
    - golint
    - ifshort
    - structcheck
    - exhaustruct
    - nonamedreturns
    - wrapcheck

linters-settings:
  gosec:
    excludes:
      - G401
      - G505
      - G306
  misspell:
    ignore-words:
      - sub_payed
  whitespace:
    multi-if: true
    multi-func: false
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
          - filippo.io/edwards25519
          - golang.org/x/crypto
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  varnamelen:
    ignore-names:
      - ok

issues:
  exclude-rules:
    - linters:
        - lll
      source: ".*// "